[versions]

skyblockapi = "4.2.5"
meowdding-lib = "4.2.1"

minecraft-range = "26.2.x"
minecraft = "26.2"

sbapi-mc-version = "26.2"
fabric-api = "0.152.0+26.2"

resourceful-lib = "5.0.0"
resourceful-config = "5.0.0"
olympus = "1.9.0"
placeholders = "3.1.0-beta.1+26.2"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-26.2", version.ref = "resourceful-lib" }
resourceful-config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-26.2", version.ref = "resourceful-config" }

olympus = { module = "earth.terrarium.olympus:olympus-fabric-26.2", version.ref = "olympus" }
placeholders = { module = "eu.pb4:placeholder-api", version.ref = "placeholders" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
