[versions]

fabric-loader = "0.18.2"
fabric-language-kotlin = "1.13.10+kotlin.2.3.20"

kotlin = "2.3.0"
kotlin-gradle-plugin = "2.3.0"
kotlin-symbol-processor = "2.3.5"

hypixelapi = "1.0.2+build.1+mc26.1"

rconfigkt = "4.0.0-beta.1"

discordipc = "0.6.6"

fabric-loom = "1.15-SNAPSHOT"

[libraries]

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }

resourcefulkt-config = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-26.1-rc-1", version.ref = "rconfigkt" }

discordipc = { module = "io.github.vyfor:kpresence", version.ref = "discordipc" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin-gradle-plugin" }

[plugins]
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }

fabric-loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
